In [113]:
import pickle
import gzip

#how be able to iterate through all of the different files
vals_dict = {'tfs':[None, 0.01, 0.05, 0.1, 0.5, 0.75 ],
'n': [0.1, 0.25, 0.5, 0.75, 0.9], 'k':[1,10,40,200]  }



In [15]:
for key, params in vals_dict.items():
    for par in params:
        if par ==None:
            par = "None"
        all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        break
    break

In [16]:
del df

In [19]:
len(text)

4

In [21]:
text[0].shape

(25, 250)

In [12]:
rand_selects

array([ 5139,  3768,  3912, 14879,  4848, 13605,  7192,  4237, 11121,
        1026,  8831,  8895,  9386,  8417, 10926, 12170,   689, 11198,
        5558, 14495,  9743,  3571, 10490, 15136, 14165,  5939,  1996,
        5117,  7427,  1754,  8566,  8908,  3902,  7495, 11357,  5927,
       14523,  7528, 11829, 12279, 14369,  3906,  3151,  9904,  9827,
       12211, 12933,  3498,  9235,  6581, 14304, 14487,  5428, 11345,
        7185, 10007,  5472,  4487,   540, 11144,  7012,  4381, 12873,
        7952,  2756, 11068, 15111,  6720, 10393,  3551, 14269, 12066,
        2866, 10860,  7183, 11955, 13936,  7243, 14593,  9269,  3369,
        9500,  2613,  1021,  3822,  7491,  9998,  6938,  1582,  7865,
        2662,  9045,  1324, 11431,  9123, 11092,  2847, 13290,   653,
        1838])

In [22]:
all_logits[0].shape

(25, 50257, 150)

In [8]:
all_logits[0][:,0,0]

array([-111.37936 ,    5.993324, -124.22533 , -133.7251  ,  -18.43812 ,
        -87.03779 ,  193.62799 , -103.28502 ,  -42.595085,  -54.76678 ,
       -124.7779  , -125.51141 ,  -78.802734, -150.16475 ,  -79.78396 ,
       -115.191864,  -73.8743  ,  -30.89286 , -119.48405 , -147.27014 ,
        -77.28897 ,   47.17818 , -112.41978 ,  -89.85373 ,  -46.095333],
      dtype=float32)

In [114]:
import numpy as np 
import pandas as pd
prompts=pd.read_csv('test_dataframe_500primer.csv') # the text has the prompts so dont need this. 

# Convert all of the numbers text from all of the different models into one dataframe with all of the prompts and the produced text separated out

In [25]:
text[0][0]

array([   58, 25527,    60,   921,   804,   503,   379,   262,  6016,
        7588,   286,   262,  1748,   290,  4240,   703,   345,  1683,
        6348,   510,    13,   220,   198,   383,  7588,  9280,  1973,
         262,  6180,  6766,    13,   921,   460,   766,   262,  6832,
         287,   262,  5253,    11,   617,  7588,  6225,   286,   355,
         262,  7000,  1969,   866,    13,   921,  4240,   703,   428,
         477,  3022,    11,   618,   750,  2279,  1487,    30,   220,
         198,   220,   198,  1649,   750,  1635,  5832,     9,  1487,
          30,   220,   198,   220,   198, 11075,   318,  4642,   257,
        1200,    13,  2773,  1663,   510,  5443,   621,  1854,    13,
        2773,   466,   299,   470,  1663,   510,   379,   477,    13,
       19347,  1208,   319,   262,  4417,   286,   262,  2323,    26,
         257,  1110,  8318,   416,  6364,  1973,   262,  1755,  6766,
          13,   921,  4240,   508,   318,  1016,   284,  1663,   510,
         262, 14162,

In [115]:
# used to decode:

from decodeLogits import *
batch = 0
ind = 0
'''
tokens = []
for j in range(text[0].shape[2]):
    tokens.append(np.argmax(df[0][ind, :, j]))'''
decoder_text(text[batch][ind])

"[WP] You look out at the bright lights of the city and wonder how you ever grew up. \n The lights dance across the evening sky. You can see the buildings in the distance, some lights turning of as the stores close down. You wonder how this all happened, when did everything change? \n \n When did *you* change? \n \n Everyone is born a child. Some grow up faster than others. Some do n't grow up at all. Hours later, it's your turn.\n It's my turn.  It seems so very different to have done all of this from day one. \n \nYou're just so lonely in your sleep.  You haven't been able to stop thinking about it all day. It seems like something you always wanted just wouldn't happen. \n \n \xa0 I've always dreamed of becoming the strongest guy in school, a powerful male, the champion athlete. \n I've always wanted to do more but I've always felt like nothing was my best. This year it didn't go as long as expected as I just couldn't stay awake. I'm sure I have more dreams and I'm sure they will lea

In [ ]:
for key, params in vals_dict.items():
    for par in params:
        if par ==None:
            par = "None"
        all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        break
    break

In [29]:
prompts = []

prompt_length = 100
for batch in text:
    for entry in batch:
        prompts.append( decoder_text(entry[0:prompt_length]) )
        
gs = pd.DataFrame({'Prompt':prompts})

In [30]:
gs.head()

Prompt
0  [WP] You look out at the bright lights of the ...
1  [FF] - 250 Words; 2 months Reddit Gold prize \...
2  [WP] The shortest story ever told. Once upon a...
3  [WP] Stockholm syndrome, but the other way aro...
4  [WP] Your grandparents always playfully bicker...

In [34]:
 vals_dict.items()
    
I also need to store the sorted indices of the differnet words

dict_items([('tfs', [None, 0.01, 0.05, 0.1, 0.5, 0.75]), ('n', [0.1, 0.25, 0.5, 0.75, 0.9]), ('k', [1, 10, 40, 200])])

In [116]:
for key, params in vals_dict.items():
    for par in params:
        if par == 200:
            continue
        if par ==None:
            par = "None"
        #all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        generated_output = []
        for batch in text:
            for entry in batch:
                generated_output.append(decoder_text(entry[prompt_length:]))
        col_name = 'Samp Type:'+key+' Param:'+str(par)
        gs[col_name] = generated_output
gs.head()

Prompt  \
0  [WP] You look out at the bright lights of the ...   
1  [FF] - 250 Words; 2 months Reddit Gold prize \...   
2  [WP] The shortest story ever told. Once upon a...   
3  [WP] Stockholm syndrome, but the other way aro...   
4  [WP] Your grandparents always playfully bicker...   

                            Samp Type:tfs Param:None  \
0   pass on the surface of the ground; a day pass...   
1   I have given it a few more days? \n\n \n\n I ...   
2   this, because it was evil, so the genie was n...   
3   taken her to the hospital and we gave her a s...   
4   was Swedish and his first name had no resembl...   

                            Samp Type:tfs Param:0.01  \
0   go by in silence, and short workdays go by qu...   
1  've cut it down a bit sooner, I guess. Or he'l...   
2   the genie's station. He wished for happiness....   
3  , at 5 minutes before the deadline, we stole a...   
4  , was in reality half Swedish, half Norwegian,...   

                            Samp Type:tfs Param:0.05  \
0   go by in silence, and short workdays go by qu...   
1  've cut it down a bit sooner, I guess. Or he'l...   
2   the genie's station\nDerbellan\n(12,050 votes...   
3  , at 5 minutes before the deadline, we stole a...   
4  , was in reality half Swedish, half Norwegian,...   

                             Samp Type:tfs Param:0.1  \
0   go by in silence, and short workdays go by qu...   
1  've cut it down a bit sooner, I guess. Or he'l...   
2   the genie's station\nDerbellan You are that i...   
3  , at 5 minutes before the deadline, we stole a...   
4  , was in reality half Swedish, half Norwegian,...   

                             Samp Type:tfs Param:0.5  \
0   go by in silence, and short workdays go by qu...   
1  've cut it down a bit sooner, I guess. Or he'l...   
2   the genie's station\nDerbell found his whole ...   
3  , at 5 minutes before the deadline--'' \n \n `...   
4  , was in reality half Swedish, half Norwegian,...   

                            Samp Type:tfs Param:0.75  \
0   go by in silence, and short workdays go by qu...   
1  've cut it down a bit sooner, I guess. Or he'l...   
2   the genie's station\nDerbell found his whole ...   
3  , at 5 minutes before the deadline--'' \n \n `...   
4  , was in reality half Swedish, half Norwegian,...   

                               Samp Type:n Param:0.1  \
0   pass, days pass, years pass. \n \n\nThe world...   
1   I go back to the cave? \n \n \n \n\n \n\n \n\...   
2   anything. He wished for a lamp. And the genie...   
3   she's with us now. She's safe. She's safe. Sh...   
4  , was a character from a movie called "The Dan...   

                              Samp Type:n Param:0.25  \
0   pass by, days pass by, weeks pass by. You're ...   
1   I go to the store and buy some more? \n \n \n...   
2   anything. He wished for a lamp. And the genie...   
3   we're going to take her back to the States. Y...   
4  , was not only a fictional character, but also...   

                               Samp Type:n Param:0.5  \
0   pass by. They're busy with their day. The thi...   
1   I not just stay here and wait for it to dry? ...   
2   a good guy. And he did not wish for a good gu...   
3   you didn't tell us?'' \n \n ``Why did you lea...   
4  , was not Swedish at all. It was actually Dani...   

                              Samp Type:n Param:0.75  \
0   have passed. \n In the rain, blood trickles d...   
1   I risk dropping it? Oh well, it's my fault, I...   
2   a good world. For he wished to live in a smal...   
3   you didn't pay for her? '' \n\n ``Yeah, we di...   
4  , was not that likable at all, but was merely ...   

                               Samp Type:n Param:0.9  \
0   have passed. you're more tired than you were ...   
1   I risk dropping it? Oh well, it's my fault, I...   
2   so many things that there were centuries wort...   
3  ... you know, bought her flowers too. ''\n\nCa...   
4  , was not that likable at all, but was merely ...   

  

In [117]:
gs.shape

(100, 15)

In [118]:
import numpy as np
select_a_random_prompt = np.random.choice(gs.shape[0])
select_random_generation_methods = np.random.choice(gs.shape[1]-1, size =gs.shape[1]-1, replace=False )+1
select_random_generation_methods = np.insert(select_random_generation_methods, 0, 0)
print(select_a_random_prompt)
select_random_generation_methods

78


array([ 0,  4,  8,  1,  2, 14,  3,  7,  9,  5, 12, 11, 13, 10,  6])

In [119]:
with open('test_blind_output3.txt', 'w') as file: 
    for ind, out in enumerate(gs.iloc[select_a_random_prompt,select_random_generation_methods].tolist()):
        if ind ==0:
            file.write('Prompt: \n \n')
        file.write(out)
        
        file.write('\n')
        file.write('================== \n')
        if ind == gs.shape[1]-1: # dont write random generation at the end. 
            continue
        file.write('Random Generation: '+str(ind)+' \n \n')



Seems like need a larger n to have something that isnt just degenerate. but then need to sample to get something that is good. N of 0.75 or 0.5? K seems to be doing quite well. TFS is generating some strange things? I want to see the prob distribution it makes at each point. 

In [120]:
print(select_a_random_prompt)
select_random_generation_methods

78


array([ 0,  4,  8,  1,  2, 14,  3,  7,  9,  5, 12, 11, 13, 10,  6])

In [121]:
gs.iloc[select_a_random_prompt,select_random_generation_methods]

Prompt                      [WP] Write a story where the antagonist is doi...
Samp Type:tfs Param:0.1      distill through the glass base of the weapon ...
Samp Type:n Param:0.25       open my mouth to scream, but the syringe is a...
Samp Type:tfs Param:None     hold it in front of my eyes ’ and look down a...
Samp Type:tfs Param:0.01     distill through the glass base of the weapon ...
Samp Type:k Param:40         open my mouth to try and scream out what I ca...
Samp Type:tfs Param:0.05     distill through the glass into a drop that I ...
Samp Type:n Param:0.1        look up at the weapon. It's a long, thin, bla...
Samp Type:n Param:0.5        open my mouth to scream, but I can't make it ...
Samp Type:tfs Param:0.5      distill through the glass base of the weapon ...
Samp Type:k Param:1          look up at the weapon. It's a small, black, m...
Samp Type:n Param:0.9        open my mouth and exhale slowly, hoping that ...
Samp Type:k Param:10         open my mouth to try and scream out

In [122]:
gs.iloc[select_a_random_prompt,0]

'[WP] Write a story where the antagonist is doing something obviously horrible, but by the end of the story make me want to side with him over the good guy. \n **BOOM** \n \n **CRASH** \n \n I fall hard on the pavement. Taking a few seconds, I scramble to my feet, coughing smoke out of my lungs. The weapon is a few feet away. It ’ s a large syringe filled with a purple liquid. I'

In [123]:
choose_prompt =rand_selects[select_a_random_prompt]
choose_prompt

14593

In [124]:
prompts.head()

test_source  \
0  [WP] Leonardo DiCaprio in a fit of rage begins...   
1    [CW] Kill the writer in first-person narrative.   
2  [EU] Sean Bean has a hard time leaving his rol...   
3  [WP] A kid doodling in a math class accidental...   
4  [WP] As a Space marine you have an allowance o...   

                                         test_target  \
0  The wet marble floor pressed on his cheek like...   
1  It's been three days since my boyfriend pissed...   
2  George fled. Not terrifically fast, not at his...   
3  It was dark and Levi was pretty sure he was ly...   
4  ``Hi dad! ''\n \n The words snap me from my th...   

                                              Prompt  
0  [WP] Leonardo DiCaprio in a fit of rage begins...  
1  [CW] Kill the writer in first-person narrative...  
2  [EU] Sean Bean has a hard time leaving his rol...  
3  [WP] A kid doodling in a math class accidental...  
4  [WP] As a Space marine you have an allowance o...

In [125]:
print(prompts.iloc[choose_prompt].test_target)

**BOOM** 
 
 **CRASH** 
 
 I fall hard on the pavement. Taking a few seconds, I scramble to my feet, coughing smoke out of my lungs. The weapon is a few feet away. It ’ s a large syringe filled with a purple liquid. I pick it up and keep running. Suddenly, I hear an explosion behind me. I can ’ t help but turn around. 
 
 Cataclysm is floating through the street towards me, fire and smoke trailing in his path. He has a wicked smile on his face. He raises a hand at me, and a bolt of lightning travels right by me. I stumble backwards and turn down a side street. Luckily, I knew these roads like the back of my hand. 
 
 I grew up here in Lower Echelon. It ’ s where the scum of humanity come to die. But it is my home, and I wouldn ’ t trade it for anything. I was left here for dead as a child, but I survived, even flourished. Over the years, Echelon grew, and so did the population. The buildings became closer and higher until you couldn ’ t see the sky anymore. It got so bad that the polic