In [1]:
import pickle
import gzip

#how be able to iterate through all of the different files

#updated
vals_dict = {'tfs':[0.25, 0.75, 0.9, 0.95, 0.99], 'flat':[0.01, 0.02, 0.05],
'n': [0.1, 0.25, 0.5, 0.75, 0.9], 'k':[1,10,40,200]  }



In [2]:
for key, params in vals_dict.items():
    for par in params:
        if par ==None:
            par = "None"
        #all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        break
    break

In [3]:
len(text)

4

In [4]:
text[0].shape

(25, 250)

In [5]:
rand_selects

array([ 5139,  3768,  3912, 14879,  4848, 13605,  7192,  4237, 11121,
        1026,  8831,  8895,  9386,  8417, 10926, 12170,   689, 11198,
        5558, 14495,  9743,  3571, 10490, 15136, 14165,  5939,  1996,
        5117,  7427,  1754,  8566,  8908,  3902,  7495, 11357,  5927,
       14523,  7528, 11829, 12279, 14369,  3906,  3151,  9904,  9827,
       12211, 12933,  3498,  9235,  6581, 14304, 14487,  5428, 11345,
        7185, 10007,  5472,  4487,   540, 11144,  7012,  4381, 12873,
        7952,  2756, 11068, 15111,  6720, 10393,  3551, 14269, 12066,
        2866, 10860,  7183, 11955, 13936,  7243, 14593,  9269,  3369,
        9500,  2613,  1021,  3822,  7491,  9998,  6938,  1582,  7865,
        2662,  9045,  1324, 11431,  9123, 11092,  2847, 13290,   653,
        1838])

In [7]:
import numpy as np 
import pandas as pd
prompts=pd.read_csv('test_dataframe_500primer.csv') # the text has the prompts so dont need this. 

# Convert all of the numbers text from all of the different models into one dataframe with all of the prompts and the produced text separated out

In [8]:
text[0][0]

array([   58, 25527,    60,   921,   804,   503,   379,   262,  6016,
        7588,   286,   262,  1748,   290,  4240,   703,   345,  1683,
        6348,   510,    13,   220,   198,   383,  7588,  9280,  1973,
         262,  6180,  6766,    13,   921,   460,   766,   262,  6832,
         287,   262,  5253,    11,   617,  7588,  6225,   286,   355,
         262,  7000,  1969,   866,    13,   921,  4240,   703,   428,
         477,  3022,    11,   618,   750,  2279,  1487,    30,   220,
         198,   220,   198,  1649,   750,  1635,  5832,     9,  1487,
          30,   220,   198,   220,   198, 11075,   318,  4642,   257,
        1200,    13,  2773,  1663,   510,  5443,   621,  1854,    13,
        2773,   466,   299,   470,  1663,   510,   379,   477,    13,
       19347,  1208,   319,   262,  4417,   286,   262,  2323,    26,
         257,  1110,  8318,   416,  6364,  1973,   262,  1755,  6766,
          13,   921,  4240,   508,   318,  1016,   284,  1663,   510,
         262, 14162,

In [9]:
# used to decode:

from decodeLogits import *
batch = 0
ind = 0
'''
tokens = []
for j in range(text[0].shape[2]):
    tokens.append(np.argmax(df[0][ind, :, j]))'''
decoder_text(text[batch][ind])

'[WP] You look out at the bright lights of the city and wonder how you ever grew up. \n The lights dance across the evening sky. You can see the buildings in the distance, some lights turning of as the stores close down. You wonder how this all happened, when did everything change? \n \n When did *you* change? \n \n Everyone is born a child. Some grow up faster than others. Some do n\'t grow up at all. Hours pass on the surface of the ground; a day passes by slowly across the night sky. You wonder who is going to grow up the fastest. \n \n\n\xa0"You\'ve got a job today, then?"\n"Sure. It\'s just a little more complicated than I expected, but it\'s all good." \nYou watch the bright moonlight dancing through the street lamps. It\'s bright and there aren\'t any buildings in it. In a little bit. That doesn\'t mean it\'s not exciting. The streets are empty, there\'s no traffic and everyone\'s just talking. It\'s quiet and still and you can feel how beautiful things are. It\'s like you\'ve g

In [10]:
for key, params in vals_dict.items():
    for par in params:
        if par ==None:
            par = "None"
        all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        break
    break

In [11]:
prompts = []
rest_of_prompts = []
prompt_length = 100
generation_length = 150+200 # just for safety
for batch in text:
    for entry in batch:
        prompts.append( decoder_text(entry[0:prompt_length]) )
        rest_of_prompts.append( decoder_text(entry[prompt_length:prompt_length+generation_length]) )
        
gs = pd.DataFrame({'Prompt':prompts, 'Rest of Prompt':rest_of_prompts})

In [12]:
gs.head()

Prompt  \
0  [WP] You look out at the bright lights of the ...   
1  [FF] - 250 Words; 2 months Reddit Gold prize \...   
2  [WP] The shortest story ever told. Once upon a...   
3  [WP] Stockholm syndrome, but the other way aro...   
4  [WP] Your grandparents always playfully bicker...   

                                      Rest of Prompt  
0   pass on the surface of the ground; a day pass...  
1   I have given it a few more days? \n\n \n\n I ...  
2   this, because it was evil, so the genie was n...  
3   taken her to the hospital and we gave her a s...  
4   was Swedish and his first name had no resembl...

### Making the human prompt completions so that the perplexity can be scored

In [13]:
gs.to_csv('Human_StoryPrompts_Completion.csv', index=False, columns =['Rest of Prompt'])

In [37]:
pd.read_csv('Human_StoryPrompts_Completion.csv')

Rest of Prompt
0    pass on the surface of the ground; a day pass...
1    I have given it a few more days? \n\n \n\n I ...
2    this, because it was evil, so the genie was n...
3    taken her to the hospital and we gave her a s...
4    was Swedish and his first name had no resembl...
5    appeared on the screen. He stared at the scre...
6    of his life.\n\nThe boy's face was filled wit...
7    n-dimensional space by some arbitrary combina...
8    the mountains. A little further on it's quiet...
9    whale's belly. The answer was found in the wh...
10   and then she'll get pregnant one more time, a...
11   online research and find out what was going o...
12   profile behind the cauldron and my back turne...
13   A man with a dream has gone mad. His wealth, ...
14  You would have thought that in the last centur...
15   That was the first city I've ever discovered....
16  A game that lets players create the perfect we...
17  il! '' She tossed the fossil at me. It hit my ...
18   out from under his chin as his head hurt agai...
19  've been here to protect.\nIf you want to give...
20   her enough that I don't care enough for her t...
21        * *                                     ...
22   one of his ancestors. That's kind of weird.''...
23  y morning for a university student, anyway: Yo...
24   and broken bones, and thousands have suffered...
25   friends in school often dismissed him for his...
26   last place he could possibly go without havin...
27   machine making life as pleasant as possible f...
28   face when he heard me. It wasn't just his fac...
29  , shaped in various ways to fit into a shape o...
..                                                ...
70  , this time, he wanted to test his power beyon...
71   message for help to everyone on the planet. E...
72   you not? '' We all sat staring at the same ob...
73   be an appropriate place for this? Even I coul...
74  , with a look of anger and disappointment on h...
75   your thirsty, and your cold, and your cold, a...
76  \n The kids had seen the janitor on a number o...
77   what was to come. This would be a very public...
78   hold it in front of my eyes ’ and look down a...
79   \n \n   The man didn't look like any of my ac...
80  fs and bankers on the screen, while her campai...
81   just from the sleep deprivation, but the ring...
82   It paused, then smiled at them both. ``I am D...
83  , making his vision impossible. He looked arou...
84   never heard of any parents suing the  church ...
85  ized the entire city of Mexico in pursuit of 0...
86  , lilac eyes. I feel her, I hear her, all of m...
87  mmm, I'm not sure. Maybe we can ask them for s...
88   says, and I nod in agreement. If he says some...
89   idea of a 'nice guy' is a guy that would rath...
90   gone.\nHe was flying at 20 miles an hour and ...
91  \n\n"Oh my god, you must be the master,"  he s...
92  . He had the bourbon and sipped it like a drun...
93   knowing how much longer I am in the ocean I l...
94   his son, and the ones like the man who would ...
95   a stupid thing and they do it to others then ...
96   moved there's no one to talk to and even thos...
97   the blood away from those white carpeting''\n...
98   are still firmly rooted.\nIt seems like this ...
99   my eyes and I realize I had a small snack bef...

[100 rows x 1 columns]

## Generating all completions for a particular random prompt

In [14]:
 vals_dict.items()
    
I also need to store the sorted indices of the differnet words

SyntaxError: invalid syntax (<ipython-input-14-ff9ac135490b>, line 3)

In [ ]:
for key, params in vals_dict.items():
    for par in params:
        if par ==None:
            par = "None"
        #all_logits = pickle.load( gzip.open('gpt-2_output/all_logits_'+key+'-sampling-type_'+par+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        text = pickle.load( gzip.open('gpt-2_output/all_text_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))
        rand_selects = pickle.load( gzip.open('gpt-2_output/prompt_rand_selections_'+key+'-sampling-type_'+str(par)+'-sampling-param_100-word-prompts_150-gen-length_100-number-of-prompts.pickle.gz', 'rb'))

        generated_output = []
        for batch in text:
            for entry in batch:
                generated_output.append(decoder_text(entry[prompt_length:]))
        col_name = 'Samp Type:'+key+' Param:'+str(par)
        gs[col_name] = generated_output
gs.head()

In [ ]:
gs.shape

In [33]:
import numpy as np
select_a_random_prompt = np.random.choice(gs.shape[0])
select_random_generation_methods = np.random.choice(gs.shape[1]-1, size =gs.shape[1]-1, replace=False )+1
select_random_generation_methods = np.insert(select_random_generation_methods, 0, 0)
print(select_a_random_prompt)
select_random_generation_methods

56


array([ 0,  2,  4, 13,  3, 11,  1, 12,  5,  9, 14, 10,  8, 15,  6,  7])

In [34]:
with open('test_blind_output1.txt', 'w') as file: 
    for ind, out in enumerate(gs.iloc[select_a_random_prompt,select_random_generation_methods].tolist()):
        if ind ==0:
            file.write('Prompt: \n \n')
        file.write(out)
        
        file.write('\n')
        file.write('================== \n')
        if ind == gs.shape[1]-1: # dont write random generation at the end. 
            continue
        file.write('Random Generation: '+str(ind)+' \n \n')



Some of the very tight ones are too close and degenerate into repeats. The prompts and stochasticity of a single generation are really hard to deal with though. it is also a lot to read in order to evaluate the quality. 
What is something I can evaluate algorithmically and where diverse beam search is outperformed? It may inherently need to be something that is long. 
Seems like there is definitely a sweet spot where dont want too many options but also dont want it to be degenerate. 

In [35]:
print(select_a_random_prompt)
select_random_generation_methods

56


array([ 0,  2,  4, 13,  3, 11,  1, 12,  5,  9, 14, 10,  8, 15,  6,  7])

In [36]:
gs.iloc[select_a_random_prompt,select_random_generation_methods]

Prompt                      [WP] Monsters under the bed exists and the wor...
Samp Type:tfs Param:0.01     like a naked zombie.\n\nI had to admit, I was...
Samp Type:tfs Param:0.1      strange. Well, I wasn't the first to wear thi...
Samp Type:k Param:10         ridiculous because of my long black hair and ...
Samp Type:tfs Param:0.05     strange. The day had been nice and sunny, but...
Samp Type:n Param:0.9        ridiculous because I was tall and tall. It di...
Samp Type:tfs Param:None     weird and I was in an emergency room. But the...
Samp Type:k Param:1          like a Halloween costume. I was surprised to ...
Samp Type:tfs Param:0.5      strange. Well, I wasn't the first to wear thi...
Samp Type:n Param:0.5        ridiculous, but they all agreed it was cool. ...
Samp Type:k Param:40         ridiculous because of my long black hair and ...
Samp Type:n Param:0.75       ridiculous, but they all agreed it looked coo...
Samp Type:n Param:0.25       weird. I was glad they didn't think

In [ ]:
gs.iloc[select_a_random_prompt,0]

In [ ]:
choose_prompt =rand_selects[select_a_random_prompt]
choose_prompt

In [ ]:
prompts.head()

In [ ]:
print(prompts.iloc[choose_prompt].test_target)